FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["src/LocalFriendzApi.UI/LocalFriendzApi.UI.csproj", "src/LocalFriendzApi.UI/"]
COPY ["src/LocalFriendzApi.Application/LocalFriendzApi.Application.csproj", "src/LocalFriendzApi.Application/"]
COPY ["src/LocalFriendzApi.Domain/LocalFriendzApi.Domain.csproj", "src/LocalFriendzApi.Domain/"]
COPY ["src/LocalFriendzApi.Infrastructure/LocalFriendzApi.Infrastructure.csproj", "src/LocalFriendzApi.Infrastructure/"]
RUN dotnet restore "./src/LocalFriendzApi.UI/LocalFriendzApi.UI.csproj"
COPY . .
WORKDIR "/src/src/LocalFriendzApi.UI"
RUN dotnet build "./LocalFriendzApi.UI.csproj" -c $BUILD_CONFIGURATION -o /app/build

FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./LocalFriendzApi.UI.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "LocalFriendzApi.UI.dll"]