# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: LocalFriendz Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Restaurar dependências
      - name: Restore dependencies
        run: dotnet restore ./LocalFriendz/LocalFriendz.sln # ajuste o caminho para o arquivo de solução ou projeto

      # Construir o projeto
      - name: Build
        run: dotnet build ./LocalFriendz/LocalFriendz.sln --no-restore # ajuste o caminho para o arquivo de solução ou projeto

      # Executar StyleCop
      - name: Run StyleCop
        id: stylecop
        run: |
          # Executa o build novamente com foco nos warnings de StyleCop
          dotnet build ./LocalFriendz/LocalFriendz.sln --no-restore > stylecop.log
          # Exibe a saída para acompanhamento
          cat stylecop.log

      # Contar Warnings StyleCop
      - name: Count StyleCop Warnings
        if: always() # Executa sempre, independente do sucesso ou falha do passo anterior
        run: |
          # Conta o número de warnings do StyleCop
          stylecop_warning_count=$(grep -i "SA" stylecop.log | wc -l)
          echo "Total StyleCop Warnings: $stylecop_warning_count"

      # Executar testes
      - name: Test
        run: dotnet test ./LocalFriendz/LocalFriendz.sln --no-build --verbosity normal # ajuste o caminho para o arquivo de solução ou projeto

