name: LocalFriendz CI/CD Workflow

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Step 3: Restore dependencies
      - name: Restore Dependencies
        run: dotnet restore ./LocalFriendz/LocalFriendz.sln # Adjust path to your solution or project file

      # Step 4: Build the project
      - name: Build Project
        run: dotnet build ./LocalFriendz/LocalFriendz.sln --no-restore # Adjust path to your solution or project file

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Run tests
      - name: Run Tests
        run: dotnet test ./LocalFriendz/tests/LocalFriendzApi.UnitTests/LocalFriendzApi.UnitTests.csproj --no-build --verbosity normal
