# This workflow will build and test a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: LocalFriendz Workflow

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Passo 1: Checkout do repositório
      - name: Step 1 Checkout Repository
        uses: actions/checkout@v4

      # Passo 2: Configurar o .NET
      - name: Step 2 Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # Passo 3: Restaurar dependências
      - name: Step 3 Restore Dependencies
        run: dotnet restore ./LocalFriendz/LocalFriendz.sln # Ajuste o caminho para o arquivo de solução ou projeto

      # Passo 4: Construir o projeto
      - name: Step 4 Build Project
        run: dotnet build ./LocalFriendz/LocalFriendz.sln --no-restore # Ajuste o caminho para o arquivo de solução ou projeto

  tests:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 5: Run tests
      - name: Run Tests
        run: dotnet test ./LocalFriendz/tests/LocalFriendzApi.UnitTests --no-build --verbosity normal # Ajuste o caminho para o seu projeto de testes
